import type { SidebarsConfig } from "@docusaurus/plugin-content-docs";

// This runs in Node.js - Don't use client-side code here (browser APIs, JSX...)

/**
 * Creating a sidebar enables you to:
 - create an ordered group of docs
 - render a sidebar for each doc of that group
 - provide next/previous navigation

 The sidebars can be generated from the filesystem, or explicitly defined here.

 Create as many sidebars as you want.
 */
import apiSidebar from "./docs/api/sidebar";

const sidebars: SidebarsConfig = {
  // Documentation générale (exclut le dossier 'api')
  documentationSidebar: [
    "intro",
    "development",
    {
      type: "category",
      label: "Backend",
      items: [{ type: "autogenerated", dirName: "backend" }],
    },
    {
      type: "category",
      label: "Frontend",
      items: [{ type: "autogenerated", dirName: "frontend" }],
    },
    {
      type: "category",
      label: "Mobile",
      items: [{ type: "autogenerated", dirName: "mobile" }],
    },
  ],
  
  // Sidebar dédiée à l'API
  // On filtre la première page (l'introduction générée) et on "aplatit" la catégorie UNTAGGED
  apiSidebar: apiSidebar
    .filter((item: any, index: number) => !(index === 0 && item.type === "doc"))
    .map((item: any) => {
      if (item.type === "category" && item.label === "UNTAGGED") {
        return item.items; // On retourne directement les éléments pour enlever le dossier
      }
      return item;
    })
    .flat() as any,

  // But you can create a sidebar manually
  /*
  tutorialSidebar: [
    'intro',
    'hello',
    {
      type: 'category',
      label: 'Tutorial',
      items: ['tutorial-basics/create-a-document'],
    },
  ],
   */
};

export default sidebars;
